export const AUTH_CONSTANTS = {
  STRATEGY_JWT: 'jwt',
  STRATEGY_LOCAL: 'local',
  IS_PUBLIC_KEY: 'isPublic',
  CONFIG_JWT_ACCESS_SECRET: 'JWT_ACCESS_SECRET',
  CONFIG_JWT_REFRESH_SECRET: 'JWT_REFRESH_SECRET',
} as const;
